### ISSUE TITLE
Testing gpmf_parser

### ISSUE THREAD

**Issue by jjy0709** [p51lee/3secondz_gpmf_parser#1]
I tested this parser with some gpmf.mp4 file but it ended with json Error.
The json file result from test only has some information of length and doesn't have any datas.
What should I do?
![스크린샷, 2021-07-02 12-12-05](https://user-images.githubusercontent.com/48046928/124215323-be24e680-db2e-11eb-977e-0769fd20270f.png)

**Comment by p51lee** [comment]
Thanks, I finally fixed that json array issue. Please check it on the main branch.

**Comment by jjy0709** [comment]
Thanks!
